namespace MentalHealth.Shared.DTOs.Chat;

/// <summary>
/// DTO for system messages generated by chat moderation (pause, resume, end)
/// </summary>
public class ChatSystemMessageDto
{
    /// <summary>
    /// Message ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The session this message belongs to
    /// </summary>
    public Guid ChatSessionId { get; set; }

    /// <summary>
    /// ID of the user who triggered the system message
    /// </summary>
    public Guid SenderId { get; set; }

    /// <summary>
    /// System message content describing the action
    /// </summary>
    public string Content { get; set; } = null!;

    /// <summary>
    /// Always true for system messages
    /// </summary>
    public bool IsSystemMessage { get; set; }

    /// <summary>
    /// When the message was created
    /// </summary>
    public DateTime SentAt { get; set; }
}
